In [3]:
import os
import sys
import random
import warnings

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

# from tqdm import tqdm
# from itertools import chain
from skimage.io import imread, imshow, imread_collection, concatenate_images
# from skimage.transform import resize
# from skimage.morphology import label

# Set someparameters
IMG_WIDTH = 128
IMG_HEIGHT = 128
IMG_CHANNELS = 3
path = './dummy/'

# warnings.filterwarnings('ignore', category=UserWarning, module='skimage')
# seed = 42
# random.seed = seed
# np.random.seed = seed

In [6]:
img_lab = imread(path + 'z_c000_p009_t0_z0_trap_8.png')
img_kaggle = imread(path + '472b1c5ff988dadc209faea92499bc07f305208dbda29d16262b3d543ac91c71.png')

In [25]:
print('Image from the lab: \n Length:')
print(len(img_lab))
print(img_lab)
print('Image from the kaggle: \n Length:')
print(len(img_kaggle))
print(img_kaggle)

Image from the lab: 
 Length:
572
[[38 38 38 ... 35 35 35]
 [38 38 38 ... 35 35 35]
 [38 38 38 ... 35 35 35]
 ...
 [37 37 37 ... 37 37 37]
 [37 37 37 ... 37 37 37]
 [37 37 37 ... 37 37 37]]
Image from the kaggle: 
 Length:
512
[[[209 202 221]
  [220 201 201]
  [222 187 179]
  ...
  [209 166 206]
  [211 170 211]
  [215 174 206]]

 [[220 207 216]
  [230 205 201]
  [228 189 179]
  ...
  [211 173 211]
  [213 173 213]
  [217 173 208]]

 [[232 214 213]
  [236 207 196]
  [234 191 184]
  ...
  [217 181 218]
  [217 178 213]
  [215 173 206]]

 ...

 [[217 168 201]
  [213 166 201]
  [211 165 201]
  ...
  [127  58 106]
  [125  55  99]
  [123  50  99]]

 [[209 160 196]
  [205 160 199]
  [203 161 201]
  ...
  [127  58 106]
  [121  57  99]
  [117  52 102]]

 [[207 156 189]
  [203 156 194]
  [203 158 199]
  ...
  [127  55 109]
  [121  53 106]
  [115  52 104]]]


In [29]:
x1 = img_kaggle[4][4]
print(len(x1))
print(x1)

3
[222 168 218]
